// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gofiber/fiber/v2"
	"template-golang/internal/db"
	"template-golang/internal/features/base"
	"template-golang/internal/features/users/handler"
	"template-golang/internal/features/users/service"
	"template-golang/pkg/redisx"
)

// Injectors from wire.go:

func InitApp() (*fiber.App, error) {
	gormDB, err := db.ConnectDB()
	if err != nil {
		return nil, err
	}
	client, err := redisx.New()
	if err != nil {
		return nil, err
	}
	baseService := base.NewBaseService(gormDB, client)
	serviceService := service.NewService(baseService)
	handlerHandler := handler.NewHandler(serviceService)
	app := NewUtschoolApp(handlerHandler)
	return app, nil
}
