name: CI/CD Pipeline

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to server (Placeholder)
        run: |
          echo "Deployment step: You would typically SSH into your server here and pull/run the latest Docker image."
          echo "Example: ssh user@your-server-ip 'cd /path/to/your/app && docker-compose pull && docker-compose up -d'"
          # Replace the above echo commands with your actual deployment commands.
          # You might need to set up SSH keys as GitHub Secrets for this step.